baseURL = 'https://lorenzo-gilly.github.io/lorenzo.science/'
languageCode = 'en-gb'
title = 'Lorenzo Gilly — Research Results'
theme = 'hugo-book'

enableGitInfo = false
disablePathToLower = true

[params]
  BookTheme = 'auto'
  BookToC = true
  BookSection = 'projects'
  BookSearch = true
  BookComments = false
  description = "Computational physics research results"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.tableOfContents]
    startLevel = 1
  [markup.highlight]
    lineNos = true
    style = "github"
