baseURL = 'https://lorenzo.science/'
languageCode = 'en-gb'
title = 'Lorenzo Gilly — Research Results'
theme = 'hugo-book'

enableGitInfo = false
disablePathToLower = true
disableKinds = ['sitemap', 'RSS']

[params]
  BookTheme = 'auto'
  BookToC = true
  BookSection = 'projects'
  BookSearch = true
  BookComments = false
  description = "Computational physics research results"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
    [markup.goldmark.extensions]
      [markup.goldmark.extensions.passthrough]
        enable = true
        [markup.goldmark.extensions.passthrough.delimiters]
          block = [['$$', '$$'], ['\[', '\]']]
          inline = [['$', '$'], ['\(', '\)']]
  [markup.tableOfContents]
    startLevel = 1
  [markup.highlight]
    lineNos = true
    style = "github"
